// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <dtkCore/dtkPlugin.h>

#include "cbbExport.h"

class CBB_WINDOWS_EXPORT cbbViewImagePluginPrivate;

// /////////////////////////////////////////////////////////////////
// cbbViewImagePlugin interface
// /////////////////////////////////////////////////////////////////

class CBB_WINDOWS_EXPORT cbbViewImagePlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     cbbViewImagePlugin(QObject *parent = 0);
     cbbViewImagePlugin(const cbbViewImagePlugin& other);
    ~cbbViewImagePlugin(void);

public:
    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
    DTK_DECLARE_PRIVATE(cbbViewImagePlugin);
};

#endif
