// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef CBBVIEWIMAGEPLUGINEXPORT_H
#define CBBVIEWIMAGEPLUGINEXPORT_H

#ifdef WIN32
    #ifdef cbbViewImagePlugin_EXPORTS
        #define CBBVIEWIMAGEPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define CBBVIEWIMAGEPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define CBBVIEWIMAGEPLUGIN_EXPORT
#endif

#endif
