// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef CBBDATAIMAGEPLUGINEXPORT_H
#define CBBDATAIMAGEPLUGINEXPORT_H

#ifdef WIN32
    #ifdef cbbDataImagePlugin_EXPORTS
        #define CBBDATAIMAGEPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define CBBDATAIMAGEPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define CBBDATAIMAGEPLUGIN_EXPORT
#endif

#endif
